language: java
jdk:
  - oraclejdk11
before_install:
  - sudo apt-get update
  - echo "Let's start Gradle Build!"
  - ./gradlew build
  - echo "We are in the Docker folder!"
script:
  - docker-compose build
before_deploy:
  echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script:
    docker tag peopleapi-docker-aws:latest 967049/peopleapi-docker-aws:latest;
    docker push 967049/peopleapi-docker-aws;
  on:
    branch: main
after_success:
  - sudo apt-get -y install python3-pip python3.7-dev
  - sudo pip3 install -U setuptools
  - sudo pip3 install -U virtualenvwrapper
  - python3 -V
  - pip3 -V
  - pip3 uninstall wheel
  - pip3 install wheel
  - pip3 install awscli --upgrade --user
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  - docker tag peopleapi-docker-aws:latest $IMAGE_REPO_URL:latest
  - docker push $IMAGE_REPO_URL:latest
notifications:
  email: false