sudo: required
dist: bionic
language: java
python:
  - "3.6"
jdk:
  - oraclejdk11
before_install:
  - sudo apt-get update
  - echo "Let's start Gradle Build!"
  - ./gradlew build
  - echo "We are in the Docker folder!"
script:
  - docker-compose build
before_deploy:
  echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script:
    docker tag peopleapi-docker-aws:latest 967049/peopleapi-docker-aws:latest;
    docker push 967049/peopleapi-docker-aws;
  on:
    branch: main
after_success:
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install -U setuptools
  - sudo pip3 install -U virtualenvwrapper
  - python3 -V
  - pip3 -V
  - pip3 uninstall wheel
  - pip3 install wheel
  - pip3 install awscli --upgrade --user
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  - docker tag peopleapi-docker-aws:latest $IMAGE_REPO_URL:latest
  - docker push $IMAGE_REPO_URL:latest

  - sudo add-apt-repository ppa:eugenesan/ppa
  - sudo apt-get update
  - sudo apt-get install jq -y
  - curl https://raw.githubusercontent.com/silinternational/ecs-deploy/master/ecs-deploy | sudo tee -a /usr/bin/ecs-deploy
  - sudo chmod +x /usr/bin/ecs-deploy
  - echo "AWS ECS-Deploy Setup is Configured!"
  
  - ecs-deploy -c $CLUSTER_NAME -n $SERVICE_NAME -i $IMAGE_REPO_URL:$TRAVIS_JOB_ID -r $AWS_DEFAULT_REGION -t 240
notifications:
  email: false