spring:
  profiles:
    active: dev
  application:
    name: people-api
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: none
  jackson:
    default-property-inclusion: non_null

jwt:
  secret: 9331a66e-6931-4d7f-abea-15da3e06cab7
  expiration: 999999

---

spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/peopleapi_db
    username: peopleapi
    password: peopleapi

---

spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://peopleapidockeraws.cm3o8nwxvkx4.us-east-1.rds.amazonaws.com:5432/peopleapi_db
    username: peopleapi
    password: peopleapi