spring:
  profiles:
    active: dev
  application:
    name: people-api
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: none

---

spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/peopleapi_db
    username: peopleapi
    password: peopleapi

---

spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://postgresapi:5432/peopleapi_db
    username: peopleapi
    password: peopleapi